name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '22 10 * * 1'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          npm ci
          npm install @microsoft/eslint-formatter-sarif@3.1.0 --save-dev

      - name: Run ESLint and generate SARIF
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          mkdir -p reports
          npx eslint . --ext .js,.jsx,.ts,.tsx \
            --format node_modules/@microsoft/eslint-formatter-sarif/sarif.js \
            --output-file reports/eslint-results.sarif

      # (Optional) debug
      - name: List files (debug)
        run: ls -R

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/eslint-results.sarif
          wait-for-processing: true
